#!/bin/bash
# sharad.sh

set -euo pipefail
shopt -s inherit_errexit

case $1 in
        build)
                sbt build
                ;;
        test)
                sbt test
                ;;
        integration-test)
                project_dir=$(pwd)
                built_exe=$(sbt build | tail -n1)
                srt publish --input "$built_exe"
                sandbox_dir="./dist-newstyle/sandbox/"
                rm -rf "$sandbox_dir"
                mkdir -p "$sandbox_dir"
                srt install --to "$sandbox_dir"
                cd "$sandbox_dir"
                sharadd start
                cd "$project_dir"
                sbt integration-test
                sharadd stop
                ;;
esac
