#!/bin/bash
# sharadd.sh

# This script is meant to be a wrapper around the sharad web application.
# Its role is to control the starting and stopping of the application, passing options to the server

. sharadd-usage
. sharadd-start
. sharadd-stop

case $1 in

        start)
                shift
                sharadd-start
                ;;

        stop)
                shift
                sharadd-stop
                ;;
                
        restart)
                shift
                sharadd-stop
                sharadd-start
                ;;
        *)
                echo "Unknown command $1" >&2
                sharadd-usage >&2
                exit 1
                ;;
esac

