#!/bin/bash
# sharadd-start.sh

. sharad-usage
sharadd-start() {

    potential_exe=$(stat -c "%n" * | grep sharad-backend)
    
    if [[ -z $potential_exe ]]; then
            echo "Unable to find a file corresponding to the sharad server executable. This script must be run in a folder containing an executable named sharad-backend*" >&2
            exit 1
    fi
    
    if [[ $(echo $potential_exe | wc -w) != 1  ]]; then
            echo -e "Could not determine which sharad server executable to run. Found:\n" >&2
            echo "$potential_exe" >&2
            exit 1
    fi
    
    echo "Found $potential_exe as candidate to be started"
    sharad_daemon_dir="$HOME/.local/share/sharad"
    mkdir -p "$sharad_daemon_dir"
    "./$potential_exe" > ./sharad-backend.log &
    echo "$!" > "$sharad_daemon_dir/latest.pid"
}
