#!/bin/bash
# sharadd-usage.sh

sharadd-usage() {
    cat <<EOF
USAGE: sharad [COMMAND] [OPTIONS]

Wrapper around the sharad web application. Its role is to control the starting and stopping of the application, passing options to the server

Options:
  -h    Displays this usage

Commands:
  start    Starts the sharad server
EOF
}

