#!/bin/bash
# sharadd-start.sh

sharadd-stop() {

    sharad_daemon_dir="$HOME/.local/share/sharad"
    sharad_server_pidfile="$sharad_daemon_dir/latest.pid"
    pid=$(cat $sharad_server_pidfile)
    echo "Killing process $pid"
    kill -9 $pid
}
